version: "3.8"
services:
  nginxrp:
    image: nginxrp:latest
    build:
      context: .
      dockerfile: nginxrp/Dockerfile
    restart: unless-stopped
    container_name: log_rp

    ports:
      - 8888:80
    networks:
      - lognet

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: "log_nginx"
    networks:
      - lognet
    ports:
      - 81:80
    expose:
      - "80"

  node:
    image: app:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: "log_app"
    working_dir: /home/node
    environment:
      - NODE_ENV=prod
    networks:
      - lognet
    ports:
      - 3000:3000
    expose:
      - "3000"
    command: node index.js


networks:
  lognet:
    external:
      name: "lognet"
